# Generated by Django 5.1 on 2024-10-18 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour.datetour'),
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tour.feedback'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ManyToManyField(related_name='tours', to='tour.category'),
        ),
        migrations.AddField(
            model_name='tour',
            name='date_tour',
            field=models.ManyToManyField(related_name='tours', to='tour.datetour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='region',
            field=models.ManyToManyField(related_name='tours', to='tour.regiontour'),
        ),
        migrations.AddField(
            model_name='rating',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tour.tour'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour.tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tour.tourimage'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['tour', 'user'], name='tour_rating_tour_id_f3c1ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritelist',
            unique_together={('tour', 'user')},
        ),
    ]
